### ISSUE TITLE
Suggestion: Add Link to Website

### ISSUE THREAD

**Issue by NeubertJonas** [wviechtb/r-user-group#7]
I suggest to add the link to [https://wviechtb.github.io/r-user-group/](https://wviechtb.github.io/r-user-group/) to the repository details,
so it shows up next to the description on the right side.
 
Currently, there is no easy way to navigate from GitHub to the website (unless you wanna go to _Actions_ and then check where the page is deployed to).

**Comment by wviechtb** [comment]
Good suggestion. I also added links in the description itself (esp. if somebody wants to go from the website to the repo).
